version: '3.7'

networks:
  net-kafka:
    driver: bridge
    name: net-kafka

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "22181:2181"
    networks:
      - net-kafka
    env_file:
      - .env

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "19092:9092"
      - "9997:9997"
    networks:
      - net-kafka
    depends_on:
      - zookeeper
    env_file:
      - .env